name: 'CD'

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-skip-session-tagging: true

      - uses: aws-actions/setup-sam@v2

      - run: sam build --use-container

      - run: >-
          sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --parameter-overrides
          DBHost=${{ secrets.DB_HOST }}
          DBPort=${{ secrets.DB_PORT }}
          DBUser=${{ secrets.DB_USER }}
          DBPassword=${{ secrets.DB_PASSWORD }}
          DBName=${{ secrets.DB_NAME }}